apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: my-svc
  name: my-svc
spec:
  ports:
  - name: 8080-80
    nodePort: 30008
    port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: webapp-2
    release: "0-5"
  type: NodePort
status:
  loadBalancer: {}
