apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: webapp-1
    release: "0"
  name: webapp-1
spec:
  containers:
  - image: richardchesterwood/k8s-fleetman-webapp-angular:release0
    name: webapp-1
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: webapp-2
    release: "0-5"
  name: webapp-2
spec:
  containers:
  - image: richardchesterwood/k8s-fleetman-webapp-angular:release0-5
    name: webapp-2
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
