---

apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: fleetman-queue
  name: fleetman-queue
spec:
  ports:
  - name: "http"
    nodePort: 30010
    port: 8161
  - name: "endpoint"
    port: 61616
  selector:
    app: fleetman-queue
  type: NodePort
status:
  loadBalancer: {}

---

apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: fleetman-position-tracker
  name: fleetman-position-tracker
spec:
  ports:
  - name: http
    port: 8080
  selector:
    app: position-tracker
  type: ClusterIP
status:
  loadBalancer: {}

---

apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: fleetman-api-gateway
  name: fleetman-api-gateway
spec:
  ports:
  - name: http
    port: 8080
  selector:
    app: api-gateway
  type: ClusterIP
status:
  loadBalancer: {}

---

apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: webapp-service
  name: webapp-service
spec:
  ports:
  - name: http
    port: 80
  selector:
    app: webapp
  type: LoadBalancer
status:
  loadBalancer: {}

